### ISSUE TITLE
invariant function

### ISSUE THREAD

**Issue by Rredlion** [alexgo-io/alex-v1#10] opened 2021-06-14 21:31 UTC
In the yieldspace paper https://yield.is/YieldSpace.pdf, there are 4 invariant function
1. equation (16) assuming no fee
2. equation (20) assuming buying fyDai with an indirect fee factor of g
3. extension of equation (20) assuming selling fyDai with an indirect fee factor of g
4. equation (21), a non-decreasing invariant, seemingly addressing the problem of negative interest rate. However, it value would be different from the above 3 equations. As it has additional power, as well as scaled by s

Does it mean the invariant function changes with different scenario?

**Comment by fiftyeightandeight** [comment] 2021-06-15 06:27
Yes, but the first three relate to the presence of fee (and its sign depending on buy/sell) and the last relate to capital efficiency.
We would want to include fee, so (2)/(3) make sense, but the question is if we can simplify (instead of having to use two invariant equations - how does Balancer/UNI deal with this?).
For (4), we also need to extend our conclusion on (2)/(3) to allow for better capital efficiency and more work (vs (4)) is needed to allow for concentrated liquidity (ie liquidity between two arbitrary prices, rather than between 0% and +inf%).

**Comment by wallace21st** [comment] 2021-06-15 10:11
(2) and (3) are the essentially equivalent. As the author wants to constrain g<1 for notion convenience and other proofs in the later chapter, the bid and offer side are then defined as g and 1/g. I think if we can allow g to move both below 1 and above 1, one formula should be suffice.

(4) is interesting, as there is a practical side of negative interest , when fytoken is below certain threshold. There needs to be a way to address this issue.

will think more on the concentrated liquidity.

**Comment by fiftyeightandeight** [comment] 2021-06-21 15:55
Duplicate of #7

**Closed** 2021-07-05 12:50 UTC
Labels: merged, smart contract
